### ISSUE TITLE
WithInjections causes panic

### ISSUE THREAD

**Issue by wd-hopkins** [rainu/go-command-chain#2]
Calling WithInjections causes a panic and subsequent stack trace due to io.Copy being called on a command before its io streams have been created

Go version: 1.17.6

``` go
input := strings.NewReader("Hello")
err := cmdchain.Builder().
        Join("cat").WithInjections(input).
        Finalize().
        WithOutput(os.Stdout).
        Run()
```

Causes the output 
``` bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1076af7]

goroutine 18 [running]:
io.copyBuffer({0x10d96a0, 0xc000100000}, {0x0, 0x0}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:423 +0x197
io.Copy(...)
        /usr/local/go/src/io/io.go:382
os.genericReadFrom(0x10b61a0, {0x0, 0x0})
        /usr/local/go/src/os/file.go:162 +0x5d
os.(*File).ReadFrom(0x0, {0x0, 0x0})
        /usr/local/go/src/os/file.go:156 +0x55
io.copyBuffer({0x10d95a0, 0xc0000ac020}, {0x0, 0x0}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:409 +0x14b
io.Copy(...)
        /usr/local/go/src/io/io.go:382
github.com/rainu/go-command-chain.(*chain).combineStreamForCommand.func1(0x0, {0x0, 0x0})
        /Users/WHS03/go/pkg/mod/github.com/rainu/go-command-chain@v0.1.0/builder_streams.go:136 +0xaa
created by github.com/rainu/go-command-chain.(*chain).combineStreamForCommand
        /Users/WHS03/go/pkg/mod/github.com/rainu/go-command-chain@v0.1.0/builder_streams.go:133 +0x2f7
Hello
```

Caused by [builder_streams.go](https://github.com/rainu/go-command-chain/blob/main/builder_streams.go#L145) invoking io.Copy when the cmd.Stdin of /bin/cat is nil

The command does run to completion but exits with error code 2

**Comment by rainu** [comment]
Hey, thanks for reporting this issue. I have pushed a fix which should prevent this panic. Feel free to test it by yourself :)
